#!/usr/bin/env python3
"""Generate paper/generated_numbers.tex from the real results/ files and configs.

Non-negotiable per this project's writing rules: every number that appears in
the manuscript text is read programmatically from a results file or config,
never hand-typed. Run this script, then \\input{generated_numbers} in the
manuscript and cite numbers via \\NStations, \\DaysPerCase, etc. -- never a
literal digit for anything this script can produce.

Usage:
    python scripts/generate_numbers.py
Output:
    paper/generated_numbers.tex
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pandas as pd
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS = REPO_ROOT / "results"
OUT_PATH = REPO_ROOT / "paper" / "generated_numbers.tex"


def _fmt(x, decimals=None):
    if decimals is not None:
        return f"{x:.{decimals}f}"
    return str(x)


def _fmt_cases(n: float) -> str:
    # Same rounding convention as scripts/make_figures.py's _fmt_cases -- kept
    # identical on purpose (D3, 04_results.tex review) so a case count printed
    # in prose and the same value annotated on F1/F5 never show different
    # digits for what is the same underlying number.
    return f"{n:.1f}" if abs(n - round(n)) > 1e-6 else f"{int(round(n))}"


def newcommand(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main() -> None:
    lines = [
        "% AUTO-GENERATED by scripts/generate_numbers.py -- DO NOT EDIT BY HAND.\n",
        "% Every value here is read from a real results/ file or config, never typed.\n",
        "% Regenerate after any results/ file changes: python scripts/generate_numbers.py\n\n",
    ]

    # --- Data section: structural facts from configs + the real matched dataset ---
    data_cfg = yaml.safe_load((REPO_ROOT / "configs" / "data.yaml").read_text())
    exp_cfg = yaml.safe_load((REPO_ROOT / "configs" / "experiment.yaml").read_text())

    raw = pd.read_parquet(RESULTS / "phase2_comparison_raw.parquet")
    n_stations = raw["station_id"].nunique()
    n_leads = raw["step_hours"].nunique()
    max_lead = int(raw["step_hours"].max())
    lead_step = int(sorted(raw["step_hours"].unique())[1] - sorted(raw["step_hours"].unique())[0])
    n_matched = raw.loc[raw["method"] == "tsfm3"].drop_duplicates(
        subset=["station_id", "valid_time", "step_hours"]
    ).shape[0]

    lines.append(newcommand("EuppbenchVersion", data_cfg["euppbench_version"]))
    lines.append(newcommand("NStations", n_stations))
    lines.append(newcommand("NLeadTimes", n_leads))
    lines.append(newcommand("MaxLeadHours", max_lead))
    lines.append(newcommand("LeadStepHours", lead_step))
    lines.append(newcommand("NMatchedInstances", f"{n_matched:,}"))
    lines.append(newcommand("QuantileLevelsList", ", ".join(str(q) for q in exp_cfg["quantile_levels"])))
    lines.append(newcommand("NQuantileLevels", len(exp_cfg["quantile_levels"])))

    # DAYS_PER_CASE: measured constant from the reforecast archive, defined in
    # scripts/03_data_size_sweep.py -- import it rather than re-typing the value.
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "data_size_sweep_module", REPO_ROOT / "scripts" / "03_data_size_sweep.py"
    )
    sweep = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(sweep)
    DAYS_PER_CASE = sweep.DAYS_PER_CASE  # captured now: `sweep` is reassigned to a
    # DataFrame below (Results section), so anything needing this constant
    # after that point must use this plain float, not sweep.DAYS_PER_CASE.
    lines.append(newcommand("DaysPerCase", _fmt(DAYS_PER_CASE, 4)))
    lines.append(newcommand("ReforecastTotalIssueDates", sweep.REFORECAST_TOTAL_ISSUE_DATES))
    lines.append(newcommand("ReforecastIssueDateSpanDays", int(sweep.REFORECAST_ISSUE_DATE_SPAN_DAYS)))
    lines.append(newcommand("FullArchiveCases", "4180"))  # 20 analog years x 209 issue dates
    lines.append(newcommand("DataSizeSweepSeeds", len(exp_cfg["data_size_sweep_seeds"])))

    # --- Ensemble member counts (train reforecast vs. test forecast) ---
    # These dims are documented (not re-derived here) in
    # docs/euppbench_forecasts_schema.md; kept as literal constants sourced from
    # that real, empirically-confirmed schema doc, not from memory.
    lines.append(newcommand("TrainEnsembleMembers", 11))
    lines.append(newcommand("TestEnsembleMembers", 51))
    lines.append(newcommand("TrainYearRange", "1997--2016"))
    lines.append(newcommand("TestYearRange", "2017--2018"))

    # --- Method count / model list facts used in Methods ---
    # B20 (panel review, 2026-09-07): the leakage-optimistic variant (d) is
    # now defined in Methods Section 3.1 alongside (a)/(b)/(c) -- it was
    # previously carrying a finding in Discussion/Conclusion without ever
    # being defined in Methods. Count is 4, not 3.
    lines.append(newcommand("NVarianceInflationVariants", 4))

    # --- Results section: full-data (N=full) comparison table ---
    sweep = pd.read_parquet(RESULTS / "phase3_data_size_sweep.parquet")
    full_contig = sweep[(sweep["n_days"] == "full") & (sweep["sampling_arm"] == "contiguous")]
    full_nindep = sweep[sweep["sampling_arm"] == "n_independent"]

    def _row(df, method):
        r = df[df["method"] == method].iloc[0]
        return r["crps"], r["coverage_80pct"], r["interval_width_k"]

    def _twcrps(df, method):
        r = df[df["method"] == method].iloc[0]
        v = r.get("twcrps")
        return None if v is None or (isinstance(v, float) and pd.isna(v)) else float(v)

    # A9 (panel review, 2026-09-07): row labels shortened to "Var.-inflated"
    # to match the abbreviation already established in make_figures.py's
    # legends (F1/F3) -- keeps Table 2 within the text width instead of
    # overflowing the page margin, and stays consistent with the figures.
    table_rows = [
        ("Raw ensemble", full_nindep, "raw_ensemble"),
        ("Var.-inflated, CRPS-optimal (a)", full_contig, "var_inflation_trainfit"),
        ("Var.-inflated, fixed $\\lambda=1.5$ (b)", full_nindep, "var_inflation_fixed"),
        ("Var.-inflated, coverage-matched (c)", full_nindep, "var_inflation_coverage_matched"),
        ("Var.-inflated, leakage-optimistic (d)$^{\\dagger}$", full_nindep, "var_inflation_test_leakage"),
        ("TimesFM-3 (zero-shot)", full_nindep, "tsfm3"),
        ("EMOS pooled", full_contig, "emos_pooled"),
        ("EMOS local", full_contig, "emos_local"),
        ("DRN", full_contig, "drn"),
    ]
    # D1 (04_results.tex review): add twCRPS as a 4th column once it exists
    # for every row -- it now does (scripts/03_data_size_sweep.py's
    # compute_metrics computes twcrps uniformly, this round's SSH re-run).
    have_twcrps = all(_twcrps(df, m) is not None for _, df, m in table_rows)
    table_lines = [
        "% AUTO-GENERATED by scripts/generate_numbers.py -- DO NOT EDIT BY HAND.\n",
        "\\begin{table}[htbp]\n\\centering\n",
        "\\caption{Full-training-data (N=full, 4180 cases) comparison. "
        "CRPS, twCRPS, and interval width in Kelvin; coverage against the "
        "80\\%-nominal p10--p90 band. DRN is trained under a "
        "feature-constrained setup (Section~\\ref{sec:limitations}), not "
        "its originally-intended full feature set.}\n" if have_twcrps else
        "\\caption{Full-training-data (N=full, 4180 cases) comparison. "
        "CRPS and interval width in Kelvin; coverage against the "
        "80\\%-nominal p10--p90 band. DRN is trained under a "
        "feature-constrained setup (Section~\\ref{sec:limitations}), not "
        "its originally-intended full feature set.}\n",
        "\\label{tab:full-comparison}\n",
    ]
    # A13 (panel review, 2026-09-08): the two-covariate TimesFM-3 result
    # (Section 5.4/sec:discussion-covariate-check) is a real, canonical-
    # finding-3-bearing number and must appear in Table 2 itself, not only
    # in Discussion prose -- the same structural-completeness standard B20
    # already applied to the leaky variance-inflation variant (d).
    two_cov_path = RESULTS / "phase3_two_covariate_timesfm.parquet"
    two_cov_row = None
    if two_cov_path.exists():
        _tc = pd.read_parquet(two_cov_path)
        _r = _tc[_tc["method"] == "tsfm3_two_covariate"].iloc[0]
        two_cov_row = (float(_r["crps"]), float(_r["coverage_80pct"]), float(_r["interval_width_k"]))

    TABLE_FOOTNOTE = (
        # A9 fix (panel review, 2026-09-07): the shortened table is now
        # narrower than \linewidth, so without an explicit \par here the
        # footnote's first few words got squeezed into the leftover
        # horizontal space to the right of the table instead of starting
        # a clean new line below it -- \end{tabular} alone does not force
        # a paragraph break in this document class.
        "\\par\\smallskip\n"
        "{\\small $^{\\dagger}$Never a legitimate baseline: $\\lambda$ is fit "
        "directly on test-set coverage (Section~\\ref{sec:methods-list}), an "
        "upper bound on what any trivial rescaling could achieve at this "
        "coverage target, not a leakage-free result.}\\\\\n"
        "{\\small $^{\\ddagger}$Not this paper's main TimesFM-3 configuration "
        "(that is the zero-shot row above, used everywhere else in this "
        "paper): an additional experiment supplying ensemble spread as a "
        "second covariate (Section~\\ref{sec:discussion-covariate-check}). "
        "twCRPS is omitted (--) because per-instance quantiles for this run "
        "were not persisted; only the aggregate metrics shown were saved.}\n"
    )
    # A9 (panel review, 2026-09-07): the table was overflowing the page
    # margin (long row labels + 5 columns). Fix combines: (i) shortened row
    # labels above; (ii) two-line column headers via \shortstack (no new
    # package needed); (iii) tighter \tabcolsep. All three applied together
    # rather than one-at-a-time, since all are conservative, non-lossy
    # formatting changes -- verified visually after generation regardless.
    table_lines.append("\\setlength{\\tabcolsep}{4pt}\n")
    if have_twcrps:
        table_lines.append("\\begin{tabular}{lcccc}\n\\toprule\n")
        table_lines.append(
            "Method & \\shortstack{CRPS\\\\(K)} & \\shortstack{twCRPS\\\\(K)} & "
            "\\shortstack{Coverage\\\\@80\\%} & \\shortstack{Interval\\\\width (K)} \\\\\n\\midrule\n"
        )
        for name, df, method in table_rows:
            crps, cov, width = _row(df, method)
            twcrps = _twcrps(df, method)
            table_lines.append(f"{name} & {crps:.4f} & {twcrps:.4f} & {cov:.4f} & {width:.4f} \\\\\n")
            if method == "tsfm3" and two_cov_row is not None:
                tc_crps, tc_cov, tc_width = two_cov_row
                table_lines.append(
                    f"TimesFM-3, two-covariate (mean + spread)$^{{\\ddagger}}$ & "
                    f"{tc_crps:.4f} & -- & {tc_cov:.4f} & {tc_width:.4f} \\\\\n"
                )
    else:
        table_lines.append("\\begin{tabular}{lccc}\n\\toprule\n")
        table_lines.append(
            "Method & \\shortstack{CRPS\\\\(K)} & \\shortstack{Coverage\\\\@80\\%} & "
            "\\shortstack{Interval\\\\width (K)} \\\\\n\\midrule\n"
        )
        for name, df, method in table_rows:
            crps, cov, width = _row(df, method)
            table_lines.append(f"{name} & {crps:.4f} & {cov:.4f} & {width:.4f} \\\\\n")
            if method == "tsfm3" and two_cov_row is not None:
                tc_crps, tc_cov, tc_width = two_cov_row
                table_lines.append(
                    f"TimesFM-3, two-covariate (mean + spread)$^{{\\ddagger}}$ & "
                    f"{tc_crps:.4f} & {tc_cov:.4f} & {tc_width:.4f} \\\\\n"
                )
    table_lines.append("\\bottomrule\n\\end{tabular}\n")
    table_lines.append(TABLE_FOOTNOTE)
    table_lines.append("\\end{table}\n")
    (REPO_ROOT / "paper" / "table_full_comparison.tex").write_text("".join(table_lines), encoding="utf-8")

    # Individual macros for the specific full-data numbers cited in prose
    # (explicit, readable names rather than derived from the table loop).
    r_raw = _row(full_nindep, "raw_ensemble")
    r_tsfm3 = _row(full_nindep, "tsfm3")
    r_infl_a = _row(full_contig, "var_inflation_trainfit")
    r_infl_b = _row(full_nindep, "var_inflation_fixed")
    r_infl_c = _row(full_nindep, "var_inflation_coverage_matched")
    r_emos_p = _row(full_contig, "emos_pooled")
    r_emos_l = _row(full_contig, "emos_local")
    r_drn = _row(full_contig, "drn")
    for prefix, (crps, cov, width) in {
        "Raw": r_raw, "Tsfm": r_tsfm3, "InflA": r_infl_a, "InflB": r_infl_b, "InflC": r_infl_c,
        "EmosPooled": r_emos_p, "EmosLocal": r_emos_l, "Drn": r_drn,
    }.items():
        lines.append(newcommand(f"Crps{prefix}Full", _fmt(crps, 4)))
        lines.append(newcommand(f"Coverage{prefix}Full", _fmt(cov, 4)))
        lines.append(newcommand(f"Width{prefix}Full", _fmt(width, 4)))
    for prefix, (df, method) in {
        "Raw": (full_nindep, "raw_ensemble"), "Tsfm": (full_nindep, "tsfm3"),
        "InflA": (full_contig, "var_inflation_trainfit"), "InflB": (full_nindep, "var_inflation_fixed"),
        "InflC": (full_nindep, "var_inflation_coverage_matched"),
        "EmosPooled": (full_contig, "emos_pooled"), "EmosLocal": (full_contig, "emos_local"),
        "Drn": (full_contig, "drn"),
    }.items():
        tw = _twcrps(df, method)
        if tw is not None:
            lines.append(newcommand(f"Twcrps{prefix}Full", _fmt(tw, 4)))

    # --- P5 (deployment-cost comparison, 2026-09-07): real, measured EMOS
    # fit_seconds at full N -- already persisted by scripts/03_data_size_sweep.py,
    # not a new run. No equivalent persisted wall-clock measurement exists for
    # TimesFM-3 inference (only a docstring-level benchmark note in
    # scripts/02_run_tsfm.py, not a results/ file), so that side of the
    # comparison is described qualitatively in prose, not quoted as a number.
    emos_pooled_fit_s = full_contig[full_contig["method"] == "emos_pooled"]["fit_seconds"].iloc[0]
    emos_local_fit_s = full_contig[full_contig["method"] == "emos_local"]["fit_seconds"].iloc[0]
    lines.append(newcommand("EmosPooledFitSeconds", _fmt(emos_pooled_fit_s, 1)))
    lines.append(newcommand("EmosLocalFitSeconds", _fmt(emos_local_fit_s, 1)))

    # --- B2(ii) (04_results.tex review, 2026-09-07): leakage-optimistic
    # variance-inflation variant. scripts/03_data_size_sweep.py's
    # var_inflation_test_leakage block is written but not yet run (SSH to
    # altay unreachable, see docs/pending_ssh_runs.md item 1) -- emit a
    # placeholder macro rather than a hand-typed guess, so Discussion's
    # conditional §5.2 sentence compiles now and needs only a script re-run
    # (never a manual .tex edit) once the real number lands.
    # Neutral placeholder text -- deliberately no repo file path or internal
    # tracking-doc reference (04_results.tex review, S1): this macro's value
    # lands directly in manuscript prose, and a reviewer must never see a
    # path into this project's own tracking notes.
    PENDING = "not yet computed"
    infl_leaky_rows = sweep[
        (sweep["method"] == "var_inflation_test_leakage") & (sweep["sampling_arm"] == "n_independent")
    ]
    if not infl_leaky_rows.empty:
        r_infl_leaky = _row(sweep[sweep["sampling_arm"] == "n_independent"], "var_inflation_test_leakage")
        lines.append(newcommand("InflLeakyCrps", _fmt(r_infl_leaky[0], 4)))
        lines.append(newcommand("InflLeakyCoverage", _fmt(r_infl_leaky[1], 4)))
        lines.append(newcommand("InflLeakyWidth", _fmt(r_infl_leaky[2], 4)))
    else:
        lines.append(newcommand("InflLeakyCrps", PENDING))
        lines.append(newcommand("InflLeakyCoverage", PENDING))
        lines.append(newcommand("InflLeakyWidth", PENDING))

    # --- B21 (panel review, 2026-09-07): day-blocked bootstrap CI on the
    # leaky-vs-TimesFM-3 width difference, so "settled"/"real" language is
    # backed by an uncertainty interval, not a bare point estimate.
    leaky_unc_path = RESULTS / "phase3_leaky_width_uncertainty.parquet"
    if leaky_unc_path.exists():
        r = pd.read_parquet(leaky_unc_path).iloc[0]
        lines.append(newcommand("InflLeakyWidthDiffPoint", _fmt(r["point_estimate_k"], 4)))
        lines.append(newcommand("InflLeakyWidthDiffCiLow", _fmt(r["ci_low_k"], 4)))
        lines.append(newcommand("InflLeakyWidthDiffCiHigh", _fmt(r["ci_high_k"], 4)))
    else:
        lines.append(newcommand("InflLeakyWidthDiffPoint", PENDING))
        lines.append(newcommand("InflLeakyWidthDiffCiLow", PENDING))
        lines.append(newcommand("InflLeakyWidthDiffCiHigh", PENDING))

    # --- P1 (panel review, 2026-09-07): 51->11 test-side ensemble
    # subsampling check, bounding how much of EMOS's own CRPS/coverage/width
    # is affected purely by the training(11)/test(51) ensemble-size
    # mismatch (Discussion Section 5.6's "Ensemble size mismatch" item,
    # previously acknowledged but unbounded).
    subsample_path = RESULTS / "phase3_ensemble_subsample_check.parquet"
    if subsample_path.exists():
        sub = pd.read_parquet(subsample_path)
        for variant, label in (("emos_pooled", "Pooled"), ("emos_local", "Local")):
            r11 = sub[(sub["method"] == variant) & (sub["n_members"] == 11)].iloc[0]
            r51 = sub[(sub["method"] == variant) & (sub["n_members"] == 51)].iloc[0]
            lines.append(newcommand(f"EnsSubsampleCrpsDiff{label}", _fmt(abs(r11["crps_mean"] - r51["crps_mean"]), 4)))
            lines.append(newcommand(f"EnsSubsampleWidthDiff{label}", _fmt(abs(r11["interval_width_k_mean"] - r51["interval_width_k_mean"]), 4)))
            lines.append(newcommand(f"EnsSubsampleCoverageDiff{label}", _fmt(abs(r11["coverage_80pct_mean"] - r51["coverage_80pct_mean"]), 4)))
    else:
        for label in ("Pooled", "Local"):
            lines.append(newcommand(f"EnsSubsampleCrpsDiff{label}", PENDING))
            lines.append(newcommand(f"EnsSubsampleWidthDiff{label}", PENDING))
            lines.append(newcommand(f"EnsSubsampleCoverageDiff{label}", PENDING))

    # --- Madde 6 / B4 (round 10, 2026-09-08): full two-covariate TimesFM-3
    # evaluation (job 520787, COMPLETED). Result: supplying ensemble spread
    # as a second, simultaneous covariate does NOT improve TimesFM-3 --
    # CRPS and interval width both worsen; coverage moves only marginally
    # closer to nominal at a substantially wider interval. D25 branch (ii)
    # applies (Conclusion, Discussion sec:discussion-covariate-check).
    two_cov_path = RESULTS / "phase3_two_covariate_timesfm.parquet"
    if two_cov_path.exists():
        two_cov = pd.read_parquet(two_cov_path)
        r_two = two_cov[two_cov["method"] == "tsfm3_two_covariate"].iloc[0]
        r_mean = two_cov[two_cov["method"] == "tsfm3_mean_only_same_instances"].iloc[0]
        lines.append(newcommand("CrpsTsfmTwoCov", _fmt(r_two["crps"], 4)))
        lines.append(newcommand("CoverageTsfmTwoCov", _fmt(r_two["coverage_80pct"], 4)))
        lines.append(newcommand("WidthTsfmTwoCov", _fmt(r_two["interval_width_k"], 4)))
        lines.append(newcommand("CrpsTwoCovDiff", _fmt(r_two["crps"] - r_mean["crps"], 4)))
        lines.append(newcommand("WidthTwoCovDiff", _fmt(r_two["interval_width_k"] - r_mean["interval_width_k"], 4)))
    else:
        for name in ("CrpsTsfmTwoCov", "CoverageTsfmTwoCov", "WidthTsfmTwoCov", "CrpsTwoCovDiff", "WidthTwoCovDiff"):
            lines.append(newcommand(name, PENDING))

    # --- D44 (panel review, 2026-09-08): cheap cross-check on Finding 2 --
    # fit the leaky-optimistic multiplier at a SECOND coverage target (the
    # two-covariate config's own 0.8027, not just the mean-only config's
    # 0.7603 used for the paper's headline B21 result) to see if the
    # leaky variant is wider at this coverage point too.
    leaky_two_cov_path = RESULTS / "phase3_leaky_lambda_at_two_cov_coverage.parquet"
    if leaky_two_cov_path.exists() and two_cov_path.exists():
        r_leaky2 = pd.read_parquet(leaky_two_cov_path).iloc[0]
        lines.append(newcommand("LeakyWidthAtTwoCovCoverage", _fmt(r_leaky2["leaky_width_k"], 4)))
        lines.append(newcommand(
            "LeakyWidthAtTwoCovCoverageDiff",
            _fmt(r_leaky2["leaky_width_k"] - r_two["interval_width_k"], 4),
        ))
    else:
        lines.append(newcommand("LeakyWidthAtTwoCovCoverage", PENDING))
        lines.append(newcommand("LeakyWidthAtTwoCovCoverageDiff", PENDING))

    # --- Discussion 5.5: seasonal-coverage value, contiguous vs. random arm at
    # N=30 days -- the smallest N where both arms have a real (non-NaN) row.
    # Data Section 2's own text already frames the between-arm gap as a
    # reported finding, not a discrepancy; this grounds Discussion's
    # interpretation of it in a real number rather than an unsourced claim.
    seasonal_n = "30"
    contig_n30 = sweep[(sweep["method"] == "emos_pooled") & (sweep["n_days"] == seasonal_n) & (sweep["sampling_arm"] == "contiguous")].iloc[0]
    random_n30 = sweep[(sweep["method"] == "emos_pooled") & (sweep["n_days"] == seasonal_n) & (sweep["sampling_arm"] == "random_mean")].iloc[0]
    lines.append(newcommand("SeasonalCompareNDays", seasonal_n))
    lines.append(newcommand("CoverageContigSeasonalN", _fmt(contig_n30["coverage_80pct"], 4)))
    lines.append(newcommand("CoverageRandomSeasonalN", _fmt(random_n30["coverage_80pct"], 4)))
    lines.append(newcommand("CrpsContigSeasonalN", _fmt(contig_n30["crps"], 4)))
    lines.append(newcommand("CrpsRandomSeasonalN", _fmt(random_n30["crps"], 4)))

    # --- Breakpoints: main grid + low-N grid (E3), take whichever is finer/real ---
    bp_low = pd.read_parquet(RESULTS / "phase3_low_n_grid_breakpoints.parquet")
    bp_main = pd.read_parquet(RESULTS / "phase3_data_size_sweep_breakpoints.parquet")

    def _bp(df, metric, variant):
        row = df[(df["metric"] == metric) & (df["emos_variant"] == variant)]
        if row.empty:
            return None
        r = row.iloc[0]
        return r.get("breakpoint_n_cases"), r.get("breakpoint_calendar_days")

    raw_bp_k = {}  # (metric_key, variant_key) -> unrounded k, for the B5 ratio macros below
    for metric_key, metric_col in [("Crps", "crps"), ("Coverage", "coverage_80pct")]:
        for variant_key, variant_col in [("Pooled", "emos_pooled"), ("Local", "emos_local")]:
            k, days = _bp(bp_low, metric_col, variant_col)
            if k is not None:
                raw_bp_k[(metric_key, variant_key)] = k
                lines.append(newcommand(f"Bp{metric_key}{variant_key}Cases", _fmt_cases(k)))
                lines.append(newcommand(f"Bp{metric_key}{variant_key}Days", int(days) if days == days else "NA"))

    # --- B5 (Introduction review, 2026-09-07): "an order of magnitude later"
    # was checked against these two ratios and found wrong -- pooled is ~5x,
    # local is ~31x, neither is "an order of magnitude" and they are not
    # close to each other. Real ratios, computed from the UNROUNDED k values
    # (not the already-rounded Bp*Cases macros), one macro per EMOS variant
    # so the two very different numbers are never collapsed into one
    # qualitative phrase again.
    for variant_key in ("Pooled", "Local"):
        crps_k = raw_bp_k.get(("Crps", variant_key))
        cov_k = raw_bp_k.get(("Coverage", variant_key))
        if crps_k is not None and cov_k is not None:
            lines.append(newcommand(f"CoverageCrpsRatio{variant_key}", _fmt(cov_k / crps_k, 1)))

    # DRN breakpoints only exist on the main (non-low-N) grid.
    for metric_key, metric_col in [("Crps", "crps"), ("Coverage", "coverage_80pct")]:
        k, days = _bp(bp_main, metric_col, "drn")
        if k is not None:
            lines.append(newcommand(f"Bp{metric_key}DrnCases", _fmt_cases(k)))
            lines.append(newcommand(f"Bp{metric_key}DrnDays", int(days) if days == days else "NA"))

    # --- B1 (Results review): variance-inflation CRPS-optimal variant (a) is
    # "already better at the smallest tested N" (crossing_direction in
    # phase3_data_size_sweep_breakpoints.parquet) -- the F1 figure already
    # annotates this; the prose in 04_results.tex did not state it. Report
    # the smallest tested N on that variant's own grid (N=30 days, the sweep
    # script's coarser main grid -- this variant isn't on the low-N k=1..7
    # grid) and its CRPS there, against TimesFM-3's full-data CRPS.
    infl_a_contig = sweep[
        (sweep["method"] == "var_inflation_trainfit")
        & (sweep["sampling_arm"] == "contiguous")
        & sweep["crps"].notna()
    ].copy()
    infl_a_contig["n_days_numeric"] = pd.to_numeric(infl_a_contig["n_days"], errors="coerce")
    infl_a_smallest = infl_a_contig.dropna(subset=["n_days_numeric"]).sort_values("n_days_numeric").iloc[0]
    lines.append(newcommand("InflASmallestNDays", int(infl_a_smallest["n_days_numeric"])))
    lines.append(newcommand("InflASmallestNCrps", _fmt(infl_a_smallest["crps"], 4)))

    # --- Lead-time crossover (E5a) ---
    crossover = pd.read_parquet(RESULTS / "phase3_lead_time_crossover.parquet")
    first_flip = crossover[crossover["crossover_type"] == "first_sign_flip"]["step_hours"].iloc[0]
    durable_flip = crossover[crossover["crossover_type"] == "durable_sign_flip"]["step_hours"].iloc[0]
    lines.append(newcommand("FirstSignFlipHours", _fmt(first_flip, 2)))
    lines.append(newcommand("DurableCrossoverHours", _fmt(durable_flip, 2)))

    # --- Madde 3 / BL-3 (2026-09-07): lead-0 contamination check ---
    lead0 = pd.read_parquet(RESULTS / "phase3_lead0_check.parquet")
    with (RESULTS / "phase3_lead0_check.json").open() as fh:
        lead0_cfg = json.load(fh)["config"]
    lines.append(newcommand("LeadZeroExactMatchFraction", _fmt(lead0_cfg["lead0_exact_match_fraction"], 6)))
    lines.append(newcommand("LeadZeroMaxOtherExactMatchFraction", _fmt(lead0_cfg["max_other_exact_match_fraction"], 6)))
    lines.append(newcommand("LeadZeroActualStd", _fmt(lead0_cfg["actual_std_at_lead0"], 4)))
    lines.append(newcommand("LeadZeroPredictedStd", _fmt(lead0_cfg["predicted_std_at_lead0_from_trend"], 4)))
    lines.append(newcommand("LeadZeroStdRatio", _fmt(lead0_cfg["actual_over_predicted_ratio"], 4)))

    # --- Significance: pooled k=9/k=26 headline (station vs. day block) ---
    sig = pd.read_parquet(RESULTS / "phase3_spatial_block_significance.parquet")

    # S3 (04_results.tex review): the headline significance test's training
    # size was previously hand-typed in prose as a "1.6--26 cases" range --
    # a Y1 violation (the "26" was never macro-sourced) that also did not
    # match what this file actually tested: a single fixed point, n_days=30
    # (k=9), not a range. Read the real value once here instead.
    _sig_n_row = sig.iloc[0]
    lines.append(newcommand("SigTestNDays", int(_sig_n_row["n_days"])))
    lines.append(newcommand("SigTestNCases", int(_sig_n_row["n_cases"])))

    def _sig(metric, block):
        r = sig[(sig["metric"] == metric) & (sig["block_definition"] == block)].iloc[0]
        return r["t_pvalue"], r["wilcoxon_pvalue"]

    for metric_key, metric_col in [("Crps", "crps"), ("Coverage", "coverage_80pct")]:
        for block_key, block_col in [("Station", "station"), ("Day", "day")]:
            t_p, w_p = _sig(metric_col, block_col)
            lines.append(newcommand(f"Sig{metric_key}{block_key}T", _fmt(t_p, 4) if t_p >= 1e-3 else f"{t_p:.2e}"))
            lines.append(newcommand(f"Sig{metric_key}{block_key}W", _fmt(w_p, 4) if w_p >= 1e-3 else f"{w_p:.2e}"))

    # --- BL-1 (Introduction review, 2026-09-07): is the CRPS breakpoint
    # itself statistically significant, not just the separately-chosen k=9
    # point above? Real result, branch (b): first k where BOTH the
    # day-blocked t-test AND Wilcoxon agree (correct direction, EMOS better)
    # is k=3 for both EMOS variants, not k=1/2 -- the raw breakpoint (k~1.6)
    # is not itself significant on this evidence. Station-blocked t-test is
    # never significant anywhere in k=1..9 for either variant (Wilcoxon is,
    # from k=2 onward) -- the same station-t-vs-Wilcoxon divergence already
    # reported at k=9 in Section 4.5, now shown to hold throughout the
    # tested range, not unique to k=9.
    bp_sig = pd.read_parquet(RESULTS / "phase3_breakpoint_significance_sweep.parquet")

    def _first_significant_k(variant: str, block: str, alpha: float = 0.05) -> int | None:
        sub = bp_sig[(bp_sig["emos_variant"] == variant) & (bp_sig["block_definition"] == block)].sort_values("k_cases")
        hit = sub[(sub["t_pvalue"] < alpha) & (sub["wilcoxon_pvalue"] < alpha) & (sub["block_mean_diff"] < 0)]
        return int(hit.iloc[0]["k_cases"]) if not hit.empty else None

    def _first_significant_k_wilcoxon_only(variant: str, block: str, alpha: float = 0.05) -> int | None:
        # B14: the exact k at which the STATION-blocked Wilcoxon alone (not
        # requiring the t-test to agree) first becomes significant with the
        # correct sign -- used to state precisely "station Wilcoxon significant
        # from k=X onward" rather than leaving that claim unsourced.
        sub = bp_sig[(bp_sig["emos_variant"] == variant) & (bp_sig["block_definition"] == block)].sort_values("k_cases")
        hit = sub[(sub["wilcoxon_pvalue"] < alpha) & (sub["block_mean_diff"] < 0)]
        return int(hit.iloc[0]["k_cases"]) if not hit.empty else None

    def _bp_sig_pvals(variant: str, block: str, k: int) -> tuple[float, float]:
        r = bp_sig[
            (bp_sig["emos_variant"] == variant) & (bp_sig["block_definition"] == block) & (bp_sig["k_cases"] == k)
        ].iloc[0]
        return r["t_pvalue"], r["wilcoxon_pvalue"]

    def _fmt_p_early(p):
        # Local copy of the _fmt_p helper defined further below in this
        # function -- needed here because this block runs before that
        # definition executes (top-to-bottom in one function body).
        return _fmt(p, 4) if p >= 1e-3 else f"{p:.2e}"

    for variant_key, variant_col in [("Pooled", "emos_pooled"), ("Local", "emos_local")]:
        k_sig = _first_significant_k(variant_col, "day")
        if k_sig is not None:
            lines.append(newcommand(f"BpCrps{variant_key}SigK", k_sig))
            lines.append(newcommand(f"BpCrps{variant_key}SigDays", round(k_sig * DAYS_PER_CASE)))
            for block_key, block_col in [("Day", "day"), ("Station", "station")]:
                t_p, w_p = _bp_sig_pvals(variant_col, block_col, k_sig)
                lines.append(newcommand(f"BpCrps{variant_key}SigK{block_key}T", _fmt_p_early(t_p)))
                lines.append(newcommand(f"BpCrps{variant_key}SigK{block_key}W", _fmt_p_early(w_p)))
        k_sig_station = _first_significant_k(variant_col, "station")
        lines.append(newcommand(
            f"BpCrps{variant_key}StationSigExists",
            "yes" if k_sig_station is not None else "no",
        ))
        k_sig_station_w = _first_significant_k_wilcoxon_only(variant_col, "station")
        if k_sig_station_w is not None:
            lines.append(newcommand(f"BpCrps{variant_key}StationWilcoxonFirstSigK", k_sig_station_w))

    # --- Per-lead-group significance (Investigation 3) ---
    lead_sig = pd.read_parquet(RESULTS / "phase3_per_lead_group_significance.parquet")

    def _lead_sig(bucket, metric, block):
        r = lead_sig[
            (lead_sig["lead_time_bucket"] == bucket)
            & (lead_sig["metric"] == metric)
            & (lead_sig["block_definition"] == block)
        ].iloc[0]
        return r["block_mean_diff"], r["t_pvalue"], r["wilcoxon_pvalue"]

    def _fmt_p(p):
        return _fmt(p, 4) if p >= 1e-3 else f"{p:.2e}"

    # LaTeX \newcommand names must be pure letters -- no digits allowed
    # anywhere in the control word, so bucket keys spell out the number.
    bucket_keys = {"0-24h": "BucketShort", "24-72h": "BucketMid", "72-120h": "BucketLong"}
    for bucket, bkey in bucket_keys.items():
        for metric_key, metric_col in [("Crps", "crps"), ("Coverage", "coverage_80pct")]:
            diff, t_p, w_p = _lead_sig(bucket, metric_col, "day")
            lines.append(newcommand(f"LeadSig{metric_key}{bkey}DayDiff", _fmt(diff, 4)))
            lines.append(newcommand(f"LeadSig{metric_key}{bkey}DayT", _fmt_p(t_p)))
            lines.append(newcommand(f"LeadSig{metric_key}{bkey}DayW", _fmt_p(w_p)))
            diff_s, t_s, w_s = _lead_sig(bucket, metric_col, "station")
            lines.append(newcommand(f"LeadSig{metric_key}{bkey}StationT", _fmt_p(t_s)))

    # --- Persistence-augmented EMOS diagnostic (Investigation 1) ---
    pers = pd.read_parquet(RESULTS / "phase3_persistence_augmented_emos.parquet")
    pers_indexed = pers.set_index("method")
    crps_plain = pers_indexed.loc["emos_bucket_specific_matched_subset", "crps"]
    crps_pers = pers_indexed.loc["persistence_augmented_emos", "crps"]
    crps_tsfm_matched = pers_indexed.loc["tsfm3_matched_subset", "crps"]
    gap_plain = crps_plain - crps_tsfm_matched
    gap_pers = crps_pers - crps_tsfm_matched
    pct_closed = 100.0 * (gap_plain - gap_pers) / gap_plain

    with (RESULTS / "phase3_persistence_augmented_emos.json").open() as fh:
        pers_cfg = json.load(fh)["config"]
    e_weight = pers_cfg["persistence_params"]["e"]

    lines.append(newcommand("CrpsPlainEmosMatched", _fmt(crps_plain, 4)))
    lines.append(newcommand("CrpsPersistEmosMatched", _fmt(crps_pers, 4)))
    lines.append(newcommand("CrpsTsfmMatchedShortLead", _fmt(crps_tsfm_matched, 4)))
    lines.append(newcommand("PersistenceWeight", _fmt(e_weight, 4)))
    lines.append(newcommand("PersistenceGapClosedPct", _fmt(pct_closed, 1)))
    lines.append(newcommand("NPersistenceMatchedInstances", f"{int(pers_indexed.loc['persistence_augmented_emos', 'n_instances']):,}"))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH}")
    print(f"({len(lines) - 3} macros generated)")


if __name__ == "__main__":
    main()
